### ISSUE TITLE
Promscale crashing on trace ingest

### ISSUE THREAD

**Issue by niksajakovljevic** [timescale/promscale#1176]
While ingesting trace data with `otel-collector` Promscale would randomly crash with stack trace:

```
panic: BUG: unexpected error from stmtCache

goroutine 15280 [running]:
github.com/jackc/pgx/v4.(*Conn).SendBatch(0xc059743f00, 0x1792860, 0xc0c2c5d980, 0xc00b71c300, 0xc05c11ac30, 0xc05c130280)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.15.0/conn.go:801 +0x1734
github.com/jackc/pgx/v4/pgxpool.(*Conn).SendBatch(0xc03878bb50, 0x1792860, 0xc0c2c5d980, 0xc00b71c300, 0x0, 0x0)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.15.0/pgxpool/conn.go:66 +0x6f
github.com/jackc/pgx/v4/pgxpool.(*Pool).SendBatch(0xc00097e150, 0x1792860, 0xc0c2c5d980, 0xc00b71c300, 0x0, 0x0)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.15.0/pgxpool/pool.go:543 +0x8c
github.com/timescale/promscale/pkg/pgxconn.(*connImpl).SendBatch(0xc000788148, 0x1792860, 0xc0c2c5d980, 0x17777e0, 0xc00b71c300, 0x4da486, 0x620e2e18, 0x3f3bcae1323d4e60, 0x1db12002a0b7b)
	/promscale/pkg/pgxconn/pgx_conn.go:136 +0x65
github.com/timescale/promscale/pkg/pgmodel/ingestor/trace.(*traceWriterImpl).sendBatch(0xc000bf23c0, 0x1792860, 0xc0c2c5d980, 0x17777e0, 0xc00b71c300, 0x0, 0x0)
	/promscale/pkg/pgmodel/ingestor/trace/writer.go:367 +0x5f
github.com/timescale/promscale/pkg/pgmodel/ingestor/trace.(*traceWriterImpl).InsertTraces(0xc000bf23c0, 0x1792860, 0xc0c2c5d980, 0xc0cd016620, 0x0, 0x0)
	/promscale/pkg/pgmodel/ingestor/trace/writer.go:352 +0x2c14
github.com/timescale/promscale/pkg/pgmodel/ingestor.(*DBIngestor).IngestTraces(...)
	/promscale/pkg/pgmodel/ingestor/ingestor.go:80
github.com/timescale/promscale/pkg/pgclient.(*Client).IngestTraces(0xc000b50240, 0x1792860, 0xc0c2c5d980, 0xc0cd016620, 0x1768a20, 0xae03f0)
	/promscale/pkg/pgclient/client.go:230 +0x56
github.com/timescale/promscale/pkg/api.(*tracesServer).Export(0xc000b1f780, 0x1792860, 0xc0c2c5d980, 0xc0c2c696c0, 0x135b2e0, 0x0, 0x1768a20)
	/promscale/pkg/api/otlp.go:25 +0x89
go.opentelemetry.io/collector/model/otlpgrpc.rawTracesServer.Export(...)
```
It appears that that crashes only happen during higher ingestion loads once we start encountering context timeouts. As seen from the stack trace `pgx` driver panics and crashes the process. This seems like a bug on `pgx` side - obviously the code doesn't play nicely with context timeouts.

**Comment by niksajakovljevic** [comment]
I've opened related issue in PGX https://github.com/jackc/pgx/issues/1156

**Comment by niksajakovljevic** [comment]
I've run some benchmarks and they seem to run fine. Thanks.
