### ISSUE TITLE
prom-migrator panics with "proto: duplicate enum registered"

### ISSUE THREAD

**Issue by sboschman** [timescale/promscale#1425]
Version 0.0.3 of prom-migrator panics, regardless of the flags supplied:
```
panic: proto: duplicate enum registered: prometheus.ReadRequest_ResponseType
```

Example with the `version` flag, using the working v0.0.2:
```
% docker run -ti --rm timescale/prom-migrator:0.0.2 -version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
0.0.2
```

Example with v0.0.3:
```
% docker run -ti --rm timescale/prom-migrator:0.0.3 -version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
panic: proto: duplicate enum registered: prometheus.ReadRequest_ResponseType

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterEnum(...)
	/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/properties.go:520
github.com/timescale/promscale/pkg/prompb.init.0()
	/go/pkg/mod/github.com/timescale/promscale@v0.0.0-20220427110101-f90d8d289c66/pkg/prompb/remote.pb.go:408 +0x219
```

perhaps related to #551 as it mentions the same panic in the tests?

**Comment by Harkishen-Singh** [comment]
Hey @sboschman , thank you for opening the issue.

You are right, there is a problem of proto panic in prom-migrator. This https://github.com/timescale/promscale/pull/1375 fixes it. The next release `0.0.4` should be out soon, within a day or two.

If you want to try early, you can build from source or use `0.0.1`, which works fine.

**Comment by ramonguiu** [comment]
I'm pretty sure this has been fixed in [this PR](https://github.com/timescale/promscale/pull/1375).

It will be included in the next release which will go out in the next few days.
