### ISSUE TITLE
Make sure Promscale code is not reliant on search_path. everything should be schema qualified

### ISSUE THREAD

**Issue by tiehfood** [timescale/promscale#600]
If I try to run a query from Grafana on the Promscale-Backend, I get the following error:
```
level=error ts=2021-04-24T11:30:36.076Z caller=series_set.go:86 err="ERROR: function labels_info(integer[]) does not exist (SQLSTATE 42883)"
level=error ts=2021-04-24T11:30:36.078Z caller=panic.go:969 msg="runtime panic in parser" err="runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 82 [running]:\ngithub.com/timescale/promscale/pkg/promql.(*evaluator).recover(0xc00019e0e0, 0xc0001beff0, 0xc0001bf008)\n\t/Users/arye/go/src/github.com/timescale/promscale/pkg/promql/engine.go:925 +0x31e\npanic(0xd7ede0, 0x149d680)\n\t/usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/panic.go:969 +0x1b9\ngithub.com/timescale/promscale/pkg/promql.(*evaluator).eval(0xc00019e0e0, 0xf99480, 0xc00009a680, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/arye/go/src/github.com/timescale/promscale/pkg/promql/engine.go:1570 +0x105d\ngithub.com/timescale/promscale/pkg/promql.(*evaluator).Eval(0xc00019e0e0, 0xf99480, 0xc00009a680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/arye/go/src/github.com/timescale/promscale/pkg/promql/engine.go:940 +0xb2\ngithub.com/timescale/promscale/pkg/promql.(*Engine).execEvalStmt(0xc00019ee70, 0xf98f80, 0xc00012e840, 0xc000176480, 0xc00019c780, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/arye/go/src/github.com/timescale/promscale/pkg/promql/engine.go:660 +0xdfb\ngithub.com/timescale/promscale/pkg/promql.(*Engine).exec(0xc00019ee70, 0xf98f80, 0xc00012e840, 0xc000176480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/arye/go/src/github.com/timescale/promscale/pkg/promql/engine.go:561 +0x511\ngithub.com/timescale/promscale/pkg/promql.(*query).Exec(0xc000176480, 0xf98ec0, 0xc000210340, 0xc00007419e)\n\t/Users/arye/go/src/github.com/timescale/promscale/pkg/promql/engine.go:201 +0x9d\ngithub.com/timescale/promscale/pkg/api.queryRange.func1(0xf92600, 0xc00019e070, 0xc000132900)\n\t/Users/arye/go/src/github.com/timescale/promscale/pkg/api/query_range.go:104 +0xd77\ngithub.com/timescale/promscale/pkg/api.corsWrapper.func1(0xf92600, 0xc00019e070, 0xc000132900)\n\t/Users/arye/go/src/github.com/timescale/promscale/pkg/api/common.go:148 +0x7b\nnet/http.HandlerFunc.ServeHTTP(0xc0001fffe0, 0xf92600, 0xc00019e070, 0xc000132900)\n\t/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:2042 +0x44\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0xf92180, 0xc000158000, 0xc000132900)\n\t/Users/arye/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x225\nnet/http.HandlerFunc.ServeHTTP(0xc0001c7a10, 0xf92180, 0xc000158000, 0xc000132900)\n\t/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:2042 +0x44\ngithub.com/timescale/promscale/pkg/api.timeHandler.func1(0xf92180, 0xc000158000, 0xc000132900)\n\t/Users/arye/go/src/github.com/timescale/promscale/pkg/api/router.go:132 +0xc5\ngithub.com/prometheus/common/route.(*Router).handle.func1(0xf92180, 0xc000158000, 0xc000132800, 0x0, 0x0, 0x0)\n\t/Users/arye/go/pkg/mod/github.com/prometheus/common@v0.18.0/route/route.go:83 +0x283\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000176c60, 0xf92180, 0xc000158000, 0xc000132800)\n\t/Users/arye/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc7e\ngithub.com/prometheus/common/route.(*Router).ServeHTTP(0xc0001ff4c0, 0xf92180, 0xc000158000, 0xc000132800)\n\t/Users/arye/go/pkg/mod/github.com/prometheus/common@v0.18.0/route/route.go:121 +0x4c\nnet/http.(*ServeMux).ServeHTTP(0xc000211700, 0xf92180, 0xc000158000, 0xc000132800)\n\t/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:2417 +0x1ad\nnet/http.serverHandler.ServeHTTP(0xc0001580e0, 0xf92180, 0xc000158000, 0xc000132800)\n\t/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc0001a8140, 0xf98ec0, 0xc000210040)\n\t/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\t/usr/local/Cellar/go/1.15.7_1/libexec/src/net/http/server.go:2969 +0x36c\n"
level=error ts=2021-04-24T11:30:36.078Z caller=query_range.go:108 msg="unexpected error: runtime error: invalid memory address or nil pointer dereference" endpoint=query_range
```

The function prom_api.labels_info is present and defined as:
```
CREATE OR REPLACE FUNCTION prom_api.labels_info(INOUT labels integer[], OUT keys text[], OUT vals text[])
 RETURNS record
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
    SELECT
        array_agg(l.id), array_agg(l.key), array_agg(l.value)
    FROM
      label_unnest(labels) label_id
      INNER JOIN _prom_catalog.label l ON (l.id = label_id)
$function$
```

I user the latest version of Promscale.
TimescaleDB Version 2.1.1
Promscale Extension 0.1.2
PostgreSQL 13.2

**Comment by Harkishen-Singh** [comment]
I assume you see that function and the query runs in psql.

**Comment by tiehfood** [comment]
`SHOW search_path` gives me
```
"$user", public
```
should I add the `prom_api`schema?

**Comment by tiehfood** [comment]
I've added `prom_api` to the search_path, but still get the same error message

**Comment by cevian** [comment]
The search path should have been set by the promscale installation. It should have run:

**Comment by cevian** [comment]
The search path should have been set by the promscale installation. It should have run:
```
ALTER DATABASE <db> SET search_path = "$user", public, _prom_ext, prom_api, prom_metric, _prom_catalog
```
Maybe this setting is somehow being overridden in your system? Try logging in with the same user as promscale is given and running SHOW search_path

In any case, this is also a bug on our end since we shouldn't be reliant on that.
